--A)
BEGIN TRANSACTION;
DELETE FROM MATRICULA WHERE id_curso = 101;
DELETE FROM CURSO_PROFESOR WHERE id_curso = 101;
DELETE FROM CURSO WHERE id_curso = 101;
COMMIT;

--B)
BEGIN TRANSACTION;
DELETE FROM CURSO WHERE id_curso = 101;
DELETE FROM MATRICULA WHERE id_curso = 101;
DELETE FROM CURSO_PROFESOR WHERE id_curso = 101;
COMMIT;

--C)
BEGIN TRANSACTION;
UPDATE ESTUDIANTE SET email = NULL WHERE id_estudiante IN (SELECT id_estudiante FROM MATRICULA WHERE id_curso = 101);
DELETE FROM CURSO WHERE id_curso = 101;
COMMIT;

--D)
BEGIN TRANSACTION;
DELETE FROM CURSO_PROFESOR WHERE id_curso = 101;
DELETE FROM MATRICULA WHERE id_curso = 101;
DELETE FROM PROFESOR WHERE id_profesor IN (SELECT id_profesor FROM CURSO_PROFESOR WHERE id_curso = 101);
COMMIT;