A)
BEGIN TRANSACTION;
DELETE FROM USUARIO WHERE id_usuario = 42;
DELETE FROM PUBLICACION WHERE id_usuario = 42;
DELETE FROM COMENTARIO WHERE id_usuario = 42;
DELETE FROM ME_GUSTA WHERE id_usuario = 42;
COMMIT;
B)
BEGIN TRANSACTION;
DELETE FROM ME_GUSTA WHERE id_usuario = 42;
DELETE FROM COMENTARIO WHERE id_usuario = 42;
DELETE FROM PUBLICACION WHERE id_usuario = 42;
DELETE FROM USUARIO WHERE id_usuario = 42;
COMMIT;
C)
BEGIN TRANSACTION;
DELETE FROM ME_GUSTA WHERE id_usuario = 42;
DELETE FROM COMENTARIO WHERE id_publicacion IN (SELECT id_publicacion FROM PUBLICACION WHERE id_usuario = 42);
DELETE FROM PUBLICACION WHERE id_usuario = 42;
DELETE FROM USUARIO WHERE id_usuario = 42;
COMMIT;
D)
BEGIN TRANSACTION;
DELETE FROM COMENTARIO WHERE id_publicacion IN (SELECT id_publicacion FROM PUBLICACION WHERE id_usuario = 42);
DELETE FROM PUBLICACION WHERE id_usuario = 42;
DELETE FROM USUARIO WHERE id_usuario = 42;
COMMIT;