# Script para poblar la base de datos - poblacion_inicial.py
# Este script se puede ejecutar en el shell de Django usando: exec(open('script.py').read())

from app.models import Libro

libros = [
    {"titulo": "Harry Potter y la Piedra Filosofal", "autor": "J.K. Rowling", "año_publicacion": 1997, "genero": "Fantasía"},
    {"titulo": "El Hobbit", "autor": "J.R.R. Tolkien", "año_publicacion": 1937, "genero": "Fantasía"},
    {"titulo": "1984", "autor": "George Orwell", "año_publicacion": 1949, "genero": "Ficción distópica"},
    # --- 100 registros adicionales ---
    {"titulo": "Cien años de soledad", "autor": "Gabriel García Márquez", "año_publicacion": 1967, "genero": "Realismo mágico"},
    {"titulo": "Don Quijote de la Mancha", "autor": "Miguel de Cervantes", "año_publicacion": 1605, "genero": "Novela"},
    {"titulo": "La sombra del viento", "autor": "Carlos Ruiz Zafón", "año_publicacion": 2001, "genero": "Misterio"},
    {"titulo": "El amor en los tiempos del cólera", "autor": "Gabriel García Márquez", "año_publicacion": 1985, "genero": "Romance"},
    {"titulo": "Crónica de una muerte anunciada", "autor": "Gabriel García Márquez", "año_publicacion": 1981, "genero": "Novela"},
    {"titulo": "Rayuela", "autor": "Julio Cortázar", "año_publicacion": 1963, "genero": "Novela experimental"},
    {"titulo": "Ficciones", "autor": "Jorge Luis Borges", "año_publicacion": 1944, "genero": "Cuento"},
    {"titulo": "El Aleph", "autor": "Jorge Luis Borges", "año_publicacion": 1949, "genero": "Cuento"},
    {"titulo": "La casa de los espíritus", "autor": "Isabel Allende", "año_publicacion": 1982, "genero": "Realismo mágico"},
    {"titulo": "Pedro Páramo", "autor": "Juan Rulfo", "año_publicacion": 1955, "genero": "Realismo mágico"},
    {"titulo": "La ciudad y los perros", "autor": "Mario Vargas Llosa", "año_publicacion": 1963, "genero": "Novela"},
    {"titulo": "Conversación en La Catedral", "autor": "Mario Vargas Llosa", "año_publicacion": 1969, "genero": "Novela"},
    {"titulo": "La fiesta del chivo", "autor": "Mario Vargas Llosa", "año_publicacion": 2000, "genero": "Novela histórica"},
    {"titulo": "El túnel", "autor": "Ernesto Sabato", "año_publicacion": 1948, "genero": "Novela psicológica"},
    {"titulo": "Sobre héroes y tumbas", "autor": "Ernesto Sabato", "año_publicacion": 1961, "genero": "Novela"},
    {"titulo": "Bestiario", "autor": "Julio Cortázar", "año_publicacion": 1951, "genero": "Cuento"},
    {"titulo": "La invención de Morel", "autor": "Adolfo Bioy Casares", "año_publicacion": 1940, "genero": "Ciencia ficción"},
    {"titulo": "El astillero", "autor": "Juan Carlos Onetti", "año_publicacion": 1961, "genero": "Novela"},
    {"titulo": "Paradiso", "autor": "José Lezama Lima", "año_publicacion": 1966, "genero": "Novela"},
    {"titulo": "Tres tristes tigres", "autor": "Guillermo Cabrera Infante", "año_publicacion": 1967, "genero": "Novela experimental"},
    {"titulo": "Cien botellas en una pared", "autor": "Enrique Vila-Matas", "año_publicacion": 2002, "genero": "Novela"},
    {"titulo": "La literatura nazi en América", "autor": "Roberto Bolaño", "año_publicacion": 1996, "genero": "Novela"},
    {"titulo": "Los detectives salvajes", "autor": "Roberto Bolaño", "año_publicacion": 1998, "genero": "Novela"},
    {"titulo": "2666", "autor": "Roberto Bolaño", "año_publicacion": 2004, "genero": "Novela"},
    {"titulo": "El obsceno pájaro de la noche", "autor": "José Donoso", "año_publicacion": 1970, "genero": "Novela"},
    {"titulo": "La casa verde", "autor": "Mario Vargas Llosa", "año_publicacion": 1966, "genero": "Novela"},
    {"titulo": "Hombres de maíz", "autor": "Miguel Ángel Asturias", "año_publicacion": 1949, "genero": "Realismo mágico"},
    {"titulo": "El señor presidente", "autor": "Miguel Ángel Asturias", "año_publicacion": 1946, "genero": "Novela"},
    {"titulo": "Yo el Supremo", "autor": "Augusto Roa Bastos", "año_publicacion": 1974, "genero": "Novela histórica"},
    {"titulo": "Hijo de hombre", "autor": "Augusto Roa Bastos", "año_publicacion": 1960, "genero": "Novela"},
    {"titulo": "La tregua", "autor": "Mario Benedetti", "año_publicacion": 1960, "genero": "Novela"},
    {"titulo": "Gracias por el fuego", "autor": "Mario Benedetti", "año_publicacion": 1965, "genero": "Novela"},
    {"titulo": "El otoño del patriarca", "autor": "Gabriel García Márquez", "año_publicacion": 1975, "genero": "Novela"},
    {"titulo": "Del amor y otros demonios", "autor": "Gabriel García Márquez", "año_publicacion": 1994, "genero": "Novela"},
    {"titulo": "Memoria de mis putas tristes", "autor": "Gabriel García Márquez", "año_publicacion": 2004, "genero": "Novela"},
    {"titulo": "Noticia de un secuestro", "autor": "Gabriel García Márquez", "año_publicacion": 1996, "genero": "Periodismo narrativo"},
    {"titulo": "Vivir para contarla", "autor": "Gabriel García Márquez", "año_publicacion": 2002, "genero": "Autobiografía"},
    {"titulo": "El general en su laberinto", "autor": "Gabriel García Márquez", "año_publicacion": 1989, "genero": "Novela histórica"},
    {"titulo": "La mala hora", "autor": "Gabriel García Márquez", "año_publicacion": 1962, "genero": "Novela"},
    {"titulo": "Los funerales de la Mamá Grande", "autor": "Gabriel García Márquez", "año_publicacion": 1962, "genero": "Cuento"},
    {"titulo": "Ojos de perro azul", "autor": "Gabriel García Márquez", "año_publicacion": 1974, "genero": "Cuento"},
    {"titulo": "El coronel no tiene quien le escriba", "autor": "Gabriel García Márquez", "año_publicacion": 1961, "genero": "Novela"},
    {"titulo": "La hojarasca", "autor": "Gabriel García Márquez", "año_publicacion": 1955, "genero": "Novela"},
    {"titulo": "Relato de un náufrago", "autor": "Gabriel García Márquez", "año_publicacion": 1970, "genero": "Periodismo narrativo"},
    {"titulo": "El libro de los seres imaginarios", "autor": "Jorge Luis Borges", "año_publicacion": 1967, "genero": "Compendio"},
    {"titulo": "Historia universal de la infamia", "autor": "Jorge Luis Borges", "año_publicacion": 1935, "genero": "Cuento"},
    {"titulo": "El informe de Brodie", "autor": "Jorge Luis Borges", "año_publicacion": 1970, "genero": "Cuento"},
    {"titulo": "El oro de los tigres", "autor": "Jorge Luis Borges", "año_publicacion": 1972, "genero": "Poesía"},
    {"titulo": "La cifra", "autor": "Jorge Luis Borges", "año_publicacion": 1981, "genero": "Poesía"},
    {"titulo": "Los conjurados", "autor": "Jorge Luis Borges", "año_publicacion": 1985, "genero": "Poesía"},
    {"titulo": "El otro, el mismo", "autor": "Jorge Luis Borges", "año_publicacion": 1964, "genero": "Poesía"},
    {"titulo": "Para las seis cuerdas", "autor": "Jorge Luis Borges", "año_publicacion": 1965, "genero": "Poesía"},
    {"titulo": "La rosa profunda", "autor": "Jorge Luis Borges", "año_publicacion": 1975, "genero": "Poesía"},
    {"titulo": "La moneda de hierro", "autor": "Jorge Luis Borges", "año_publicacion": 1976, "genero": "Poesía"},
    {"titulo": "Adán Buenosayres", "autor": "Leopoldo Marechal", "año_publicacion": 1948, "genero": "Novela"},
    {"titulo": "Rayuela", "autor": "Julio Cortázar", "año_publicacion": 1963, "genero": "Novela"},
    {"titulo": "62/Modelo para armar", "autor": "Julio Cortázar", "año_publicacion": 1968, "genero": "Novela"},
    {"titulo": "Libro de Manuel", "autor": "Julio Cortázar", "año_publicacion": 1973, "genero": "Novela"},
    {"titulo": "Octaedro", "autor": "Julio Cortázar", "año_publicacion": 1974, "genero": "Cuento"},
    {"titulo": "Alguien que anda por ahí", "autor": "Julio Cortázar", "año_publicacion": 1977, "genero": "Cuento"},
    {"titulo": "Queremos tanto a Glenda", "autor": "Julio Cortázar", "año_publicacion": 1980, "genero": "Cuento"},
    {"titulo": "Deshoras", "autor": "Julio Cortázar", "año_publicacion": 1982, "genero": "Cuento"},
    {"titulo": "La vuelta al día en ochenta mundos", "autor": "Julio Cortázar", "año_publicacion": 1967, "genero": "Ensayo"},
    {"titulo": "Último round", "autor": "Julio Cortázar", "año_publicacion": 1969, "genero": "Ensayo"},
    {"titulo": "Los premios", "autor": "Julio Cortázar", "año_publicacion": 1960, "genero": "Novela"},
    {"titulo": "El examen", "autor": "Julio Cortázar", "año_publicacion": 1986, "genero": "Novela"},
    {"titulo": "Diario de Andrés Fava", "autor": "Julio Cortázar", "año_publicacion": 1995, "genero": "Novela"},
    {"titulo": "Divertimento", "autor": "Julio Cortázar", "año_publicacion": 1986, "genero": "Novela"},
    {"titulo": "El libro de Manuel", "autor": "Julio Cortázar", "año_publicacion": 1973, "genero": "Novela"},
    {"titulo": "La isla a mediodía", "autor": "Julio Cortázar", "año_publicacion": 1966, "genero": "Cuento"},
    {"titulo": "Las armas secretas", "autor": "Julio Cortázar", "año_publicacion": 1959, "genero": "Cuento"},
    {"titulo": "Final del juego", "autor": "Julio Cortázar", "año_publicacion": 1956, "genero": "Cuento"},
    {"titulo": "Todos los fuegos el fuego", "autor": "Julio Cortázar", "año_publicacion": 1966, "genero": "Cuento"},
    {"titulo": "La señorita Cora", "autor": "Julio Cortázar", "año_publicacion": 1966, "genero": "Cuento"},
    {"titulo": "El perseguidor", "autor": "Julio Cortázar", "año_publicacion": 1959, "genero": "Cuento"},
    {"titulo": "Casa tomada", "autor": "Julio Cortázar", "año_publicacion": 1946, "genero": "Cuento"},
    {"titulo": "Continuidad de los parques", "autor": "Julio Cortázar", "año_publicacion": 1956, "genero": "Cuento"},
    {"titulo": "La noche boca arriba", "autor": "Julio Cortázar", "año_publicacion": 1956, "genero": "Cuento"},
    {"titulo": "Axolotl", "autor": "Julio Cortázar", "año_publicacion": 1956, "genero": "Cuento"},
    {"titulo": "Las babas del diablo", "autor": "Julio Cortázar", "año_publicacion": 1959, "genero": "Cuento"},
    {"titulo": "El Sur", "autor": "Jorge Luis Borges", "año_publicacion": 1953, "genero": "Cuento"},
    {"titulo": "La muerte y la brújula", "autor": "Jorge Luis Borges", "año_publicacion": 1942, "genero": "Cuento"},
    {"titulo": "El jardín de senderos que se bifurcan", "autor": "Jorge Luis Borges", "año_publicacion": 1941, "genero": "Cuento"},
    {"titulo": "Pierre Menard, autor del Quijote", "autor": "Jorge Luis Borges", "año_publicacion": 1939, "genero": "Cuento"},
    {"titulo": "Tlön, Uqbar, Orbis Tertius", "autor": "Jorge Luis Borges", "año_publicacion": 1940, "genero": "Cuento"},
    {"titulo": "La biblioteca de Babel", "autor": "Jorge Luis Borges", "año_publicacion": 1941, "genero": "Cuento"},
    {"titulo": "El inmortal", "autor": "Jorge Luis Borges", "año_publicacion": 1947, "genero": "Cuento"},
    {"titulo": "Los teólogos", "autor": "Jorge Luis Borges", "año_publicacion": 1947, "genero": "Cuento"},
    {"titulo": "Historia del guerrero y la cautiva", "autor": "Jorge Luis Borges", "año_publicacion": 1949, "genero": "Cuento"},
    {"titulo": "Biografía de Tadeo Isidoro Cruz", "autor": "Jorge Luis Borges", "año_publicacion": 1944, "genero": "Cuento"},
    {"titulo": "Emma Zunz", "autor": "Jorge Luis Borges", "año_publicacion": 1948, "genero": "Cuento"},
    {"titulo": "La casa de Asterión", "autor": "Jorge Luis Borges", "año_publicacion": 1947, "genero": "Cuento"},
    {"titulo": "Deutsches Requiem", "autor": "Jorge Luis Borges", "año_publicacion": 1946, "genero": "Cuento"},
    {"titulo": "La escritura del dios", "autor": "Jorge Luis Borges", "año_publicacion": 1949, "genero": "Cuento"},
    {"titulo": "El Zahir", "autor": "Jorge Luis Borges", "año_publicacion": 1947, "genero": "Cuento"},
    {"titulo": "El Aleph", "autor": "Jorge Luis Borges", "año_publicacion": 1945, "genero": "Cuento"},
    {"titulo": "La intrusa", "autor": "Jorge Luis Borges", "año_publicacion": 1970, "genero": "Cuento"},
    {"titulo": "El indigno", "autor": "Jorge Luis Borges", "año_publicacion": 1970, "genero": "Cuento"},
    {"titulo": "Historia de Rosendo Juárez", "autor": "Jorge Luis Borges", "año_publicacion": 1970, "genero": "Cuento"},
]

for libro in libros:
    Libro.objects.create(**libro)
