# Generated by Django 6.1.1 on 2026-09-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('contenido', models.TextField(unique=True)),
                ('fecha_de_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_de_creacion'],
                'constraints': [models.UniqueConstraint(fields=('titulo', 'contenido'), name='unique_titulo_contenido')],
            },
        ),
    ]
