# Generated by Django 6.1.1 on 2026-09-16 05:54

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_original', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)])),
                ('sinopsis', models.TextField(blank=True)),
                ('idioma_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros_originales', to='biblioteca.idioma')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['year_original'],
            },
        ),
        migrations.CreateModel(
            name='LibroAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('PRI', 'Autor principal'), ('COA', 'Coautor'), ('TRA', 'Traductor'), ('EDI', 'Editor'), ('ADA', 'Adaptador')], default='PRI', max_length=3)),
                ('orden', models.PositiveSmallIntegerField(default=1, help_text='Orden de aparición en la portada.')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_libros', to='biblioteca.autor')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro_autores', to='biblioteca.libro')),
            ],
            options={
                'verbose_name': 'Autor de libro',
                'verbose_name_plural': 'Autores de libros',
                'ordering': ['libro', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(related_name='libros', through='biblioteca.LibroAutor', to='biblioteca.autor'),
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('NAC', 'Nacional'), ('EXT', 'Extranjera')], default='NAC', max_length=3)),
                ('sitio_web', models.URLField(blank=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editoriales', to='biblioteca.pais')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(default=1)),
                ('year_publicacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)])),
                ('isbn', models.CharField(blank=True, help_text='ISBN-13. Opcional para libros antiguos.', max_length=13, null=True, unique=True, verbose_name='ISBN')),
                ('adaptacion', models.TextField(blank=True, help_text='Descripción de la adaptación realizada (cultural, formato, etc.).')),
                ('creacion', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ediciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ediciones', to='biblioteca.editorial')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ediciones', to='biblioteca.idioma')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ediciones', to='biblioteca.libro')),
                ('territorio', models.ForeignKey(help_text='Territorio donde se distribuye esta edición.', on_delete=django.db.models.deletion.PROTECT, related_name='ediciones', to='biblioteca.pais')),
            ],
            options={
                'verbose_name': 'Edición',
                'verbose_name_plural': 'Ediciones',
                'ordering': ['libro', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='autor',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autores', to='biblioteca.pais'),
        ),
        migrations.CreateModel(
            name='TituloLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ORI', 'Original'), ('COM', 'Comercial'), ('LEG', 'Legal'), ('ALT', 'Alternativo')], default='ORI', max_length=3)),
                ('es_principal', models.BooleanField(default=False, help_text='Marca este título como el principal para mostrar en listados.')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulos_libro', to='biblioteca.idioma')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='biblioteca.libro')),
            ],
            options={
                'verbose_name': 'Título de libro',
                'verbose_name_plural': 'Títulos de libros',
                'ordering': ['libro', 'idioma', 'tipo'],
            },
        ),
        migrations.AddConstraint(
            model_name='libroautor',
            constraint=models.UniqueConstraint(fields=('libro', 'autor', 'rol'), name='unique_libro_autor_rol'),
        ),
        migrations.AddConstraint(
            model_name='edicion',
            constraint=models.UniqueConstraint(fields=('libro', 'editorial', 'idioma', 'territorio', 'numero'), name='unique_libro_editorial_idioma_territorio_numero'),
        ),
        migrations.AddConstraint(
            model_name='autor',
            constraint=models.UniqueConstraint(fields=('nombre', 'apellido'), name='unique_autor_nombre_apellido'),
        ),
        migrations.AddConstraint(
            model_name='titulolibro',
            constraint=models.UniqueConstraint(fields=('libro', 'idioma', 'tipo'), name='unique_libro_idioma_tipo'),
        ),
    ]
