# Generated by Django 6.1.1 on 2026-09-11 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_conductores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='conductor_id',
            new_name='conductor',
        ),
    ]
