# Generated by Django 6.1.1 on 2026-09-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodesAll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity', models.CharField(db_column='Entity')),
                ('currency', models.CharField(db_column='Currency')),
                ('alphabeticcode', models.CharField(blank=True, db_column='AlphabeticCode', null=True)),
                ('numericcode', models.DecimalField(blank=True, db_column='NumericCode', null=True)),
                ('minorunit', models.CharField(blank=True, db_column='MinorUnit', null=True)),
                ('withdrawaldate', models.CharField(blank=True, db_column='WithdrawalDate', null=True)),
            ],
            options={
                'db_table': 'codes-all',
                'managed': False,
            },
        ),
    ]
