# Generated by Django 6.1.1 on 2026-09-11 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cantante', models.BooleanField(default=False)),
                ('instrumento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'artistas',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
            ],
            options={
                'db_table': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='ArtistaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('creacion_registro', models.DateField(auto_now_add=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registro_de_artistas.artista')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registro_de_artistas.grupo')),
            ],
            options={
                'db_table': 'artista_grupo',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_de_artistas.grupo')),
            ],
            options={
                'db_table': 'albums',
            },
        ),
    ]
